### ISSUE TITLE
Add a new protocol which is compatible with xUDT

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#682]
There's a custom protocol based on `xUDT`, which has the same data structure of an `xUDT`.

The custom one has been deployed on mainnet

```yaml
type_id: '0x092c2c4a26ea475a8e860c29cf00502103add677705e2ccd8d6fe5af3caa5ae3'
type_script:
    code_hash: '0x00000000000000000000000000000000000000000000000000545950455f4944'
    hash_type: type
    args: '0x74f8fd146cca83d5fa2acd8a2b0bc7f0408a38b79a173c1e8ca1fbdfc95122ff'
```

There might be more and more custom protocols that are compatible with `xUDT`'s data structure. So I suggest extending the `xUDT` blocks/pages into `xUDT compatible` blocks/pages. Namely, those `xUDT compatible` tokens will be decoded and displayed as `xUDT`(maybe with a badge/id for differentiation).

Besides, the binding between `xUDT` and `unique cell` could be inherited
