### ISSUE TITLE
Integrate with SSRI Service

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#847]
**Is your feature request related to a problem? Please describe.**

There is a new `token info protocol` in the community https://talk.nervos.org/t/en-cn-ssri-executor-on-wasm-implementing-ssri-protocol-in-browsers-ssri/8732 and it will be considered the primary solution to publish token meta data(name, symbol, decimals) on-chain.

CKB Explorer should integrate with the SSRI Service to find out tokens deployed with SSRI.

**Describe the solution you'd like**

SSRI Service(https://ckb-devrel.notion.site/CKB-Explorer-UDT-1c49f5bf38208006ba22e9c5493165c2) is solely a data decoder and doesn't have persistence.

We should build a resource service based on the SSRI service to provide the following API
- `/ssris?page={page}&page_size={page_size}`: return list of ssri token info synced from the chain
- `/ssris/:id`: return token info of the specific ssri

**Additional context**
This service could be shared between CKB Explorer and our other services.

**Comment by Keith-CY** [comment]
Also, we can enable an interactive panel for tokens deployed with SSRI

Here's how ccc doing

<img width="1061" alt="Image" src="https://github.com/user-attachments/assets/ea6d1be1-86f5-4a55-8e35-e460d5601880" />

But it's too simple, the supported methods(including custom one) can be listed as Etherscan does
https://etherscan.io/token/0xdac17f958d2ee523a2206206994597c13d831ec7#readContract

<img width="1356" alt="Image" src="https://github.com/user-attachments/assets/85c1e76b-ab38-4254-be2c-492dab937f06" />

**Comment by Keith-CY** [comment]
This service should have the following APIs and run the following jobs

### APIs

- `/ssris?page{page}&page_size={page_size}`: return ssri entries, order by `desc(block_height, tx_index)`
- `/ssris/:id`: return entry of a specific ssri, the data has the following fields
```yaml
id: string
token:
  name: string
  symbol: string
  decimals: string
  icon: string
methods: string[] # response of SSRI.get_methods, split by ','
```

### Jobs

1. Iterate over the cells of `deployment`

<img width="1307" alt="Image" src="https://github.com/user-attachments/assets/fd48d4a7-cd77-4b1c-963a-e2550351585f" />

2. Save SSRI info(token meta data and response of SSRI.get_methods) into DB
```yaml
id: string # outpoint
token_name: string
token_symbol: string
token_deicmal: string
token_icon: string
methods: text
```
